### ISSUE TITLE
There's no reason to grant both socket=x11 and socket=fallback-x11

### ISSUE THREAD

**Issue by ssokolow** [flathub/com.github.vkohaupt.vokoscreenNG#3]
If you grant `--socket=x11` and `--socket=fallback-x11`, the [docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions) say that the latter will override the former, so there's no reason to grant both.

`--socket=x11` is for unconditionally granting access to X11, while `--socket=fallback-x11` is for only granting X11 when there's no Wayland available, to prevent a compromised package from preferring the less strongly sandboxed XWayland APIs over the more strongly sandboxed native Wayland API.

**Comment by Mailaender** [comment]
https://github.com/flathub/com.github.vkohaupt.vokoscreenNG/blob/master/com.github.vkohaupt.vokoscreenNG.yml#L14 only states `--socket=fallback-x11`!?

**Comment by ssokolow** [comment]
Strange. Maybe Flatpak on my end is synthesizing a `--socket=x11` when I query it. Give me a sec to investigate.

**Comment by ssokolow** [comment]
Yep. My bad. When I `flatpak run --command=sh` my way into it and examine `/app/manifest.json`, it's got no `--socket=x11`. Sorry about that.

I wonder why my Flatpak is listing `--socket=x11` as if it were explicitly specified.

**Comment by Mailaender** [comment]
https://github.com/flathub/com.github.vkohaupt.vokoscreenNG/blame/master/com.github.vkohaupt.vokoscreenNG.yml indicates no changes since my initial contribution.

**Comment by ssokolow** [comment]
\*nod* I checked `/app/manifest.json` because it's what the installed copy on my system is using and, wherever that `--socket=x11` is coming from, it's happening *after* the buildbot's `flatpak-builder` produces `/app/manifest.json` from your `com.github.vkohaupt.vokoscreenNG.yml`.

Again, sorry for bothering you.

**Comment by Mailaender** [comment]
This is above my knowledge of @flatpak. I suggest you chat with the developers at https://matrix.to/#/#flatpak:matrix.org instead.

**Comment by ssokolow** [comment]
\*nod* I'm already in there for a previous question, so I probably will after I've slept.
