### ISSUE TITLE
Rechte

### ISSUE THREAD

**Issue by vkohaupt** [flathub/com.github.vkohaupt.vokoscreenNG#6]
Hallo Mathias,
wollte die letzen zwei verunglückten commits löschen, ging aber nicht wegen fehlender Rechte.
Räume mir bitte volle Rechte ein.
Im vorraus vielen Dank.

**Comment by Mailaender** [comment]
Wir haben die gleichen Berechtigungen hier. Frag unter https://flatpak.org/about/ nach.
